image: php:7.3.0-fpm
pipelines:
  default:
    - step:
       script:
          - apt-get update && apt-get install -qy git curl libmcrypt-dev mysql-client
          - docker-php-ext-install pdo_mysql
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - ln -f -s .env.pipelines .env
          - php artisan migrate
          - php artisan serve &
          - sleep 5
          - ./vendor/bin/phpunit
          - curl -vk http://localhost:8000
          - apt-get -qq install git-ftp
          - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD $FTP_HOST -vv
       services:
         - mysql
definitions:
 services:
   mysql:
     image: mysql:5.7
     environment:
       MYSQL_DATABASE: 'homestead'
       MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
       MYSQL_USER: 'homestead'
       MYSQL_PASSWORD: 'secret'